on:
  push:
    branch:
      - master




jobs:
  build:
    runs-on: ubuntu-laster

    steps:
      - name: 'Testing Github Printing'
        run: pwd
 
      - name: 'Testing Printing'
        run: echo Abdo

      -uses: action/checkout@v3 

      -name:"Login to Docker hub"
        run: 